apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build

spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
          - "--dockerfile=/workspace/Dockerfile"
          - "--context=dir:///workspace/"
          - "--destination=172.31.37.36:5000/hello-lala:latest"
        volumeMounts:
          - name: workspace
            mountPath: /workspace
      restartPolicy: Never
      volumes:
        - name: workspace
          emptyDir: {}