name: Build and Deploy

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t saidursajol/cpp-sample-app .

      - name: Push Docker Image
        run: |
          docker push saidursajol/cpp-sample-app

      - name: Set up kube config
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | Out-File -FilePath kubeconfig.yaml -Encoding utf8
          $env:KUBECONFIG = "$(pwd)\kubeconfig.yaml"

      - name: Generate Base64 Certificates
        run: |
          echo "Generating base64-encoded certificates..."
          echo "$(kubectl config view --raw --minify -o jsonpath='{.clusters[0].cluster.certificate-authority-data}')" > ca.crt
          echo "$(kubectl config view --raw --minify -o jsonpath='{.users[0].user.client-certificate-data}')" > client.crt
          echo "$(kubectl config view --raw --minify -o jsonpath='{.users[0].user.client-key-data}')" > client.key
          echo "CA Certificate (base64):"
          cat ca.crt | base64
          echo "Client Certificate (base64):"
          cat client.crt | base64
          echo "Client Key (base64):"
          cat client.key | base64
          
      - name: deploy to k8s
        run: |
          kubectl apply -f deployment.yaml --kubeconfig=kubeconfig.yaml --validate=false
          kubectl apply -f service.yaml --kubeconfig=kubeconfig.yaml --validate=false