name: Deploy

on:
    workflow_call:
    push:
      branches:
        - main

jobs:
    deploy:
        runs-on: windows-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up KubeConfig
              run: |
                echo "${{ secrets.KUBE_CONFIG }}" | Out-File -FilePath kubeconfig.yaml -Encoding utf8
                $env:KUBECONFIG = "$(pwd)\kubeconfig.yaml"

            - name: Deploy to K8s
              run: |
                kubectl apply -f deployment.yaml
                kubectl apply -f service.yaml