name: CI/CD pipeline

on:
    workflow_call:
    push:
      branches:
        - main

jobs:
    build:
        uses: ./.github/workflows/call-build-and-push.yml
    
    deploy:
        needs: build
        uses: ./.github/workflows/deploy.yml